//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ADOS2Teams.Tests {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "16.0.0.0")]
    internal sealed partial class shtorm : global::System.Configuration.ApplicationSettingsBase {
        
        private static shtorm defaultInstance = ((shtorm)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new shtorm())));
        
        public static shtorm Default {
            get {
                return defaultInstance;
            }
        }
    }
}
